# Build with this version of Node.js
environment:
  nodejs_version: "10.15.3"

cache:
  - node_modules

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g npm@^6
  - npm install
  - npm install grunt-cli -g
  - npm install nexe -g
  - npm install mocha -g

# Post-install test scripts
test_script:
  # Output info for debugging.
  - node --version
  - npm --version
  # run tests
  - grunt test

# Build steps
build_script:
  - npm version
